IDIR =../include
# Which compiler
CC=gcc
#CC=tcc
#CFLAGS=-I$(IDIR)
C99MODE=-std=c99
LFLAGS=-lm
ODIR =obj
LDIR =../lib

_DEPS = hellomake.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))


# DO NOT DELETE

main.o: /usr/include/stdio.h
screenDiagonal.o: /usr/include/stdio.h /usr/include/math.h


